language: python
python:
- 3.6
- 3.7
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: TwdGI2s3CqckYSmfm7pq7LtCJsXZA23vh95jiTuJ+6hjGTjp2i3kAF8+Xw+i1VTDMpdtvk8ZRwAg+GP94OA/qzUr7HSiY8Lcu1/e3eivIU6u6CZfPHEJicLsVw8epfhrEC9p1tr6ftXb/ZIv7CVT3VoYzz7MAx9oXE7FGT4wObhFqLnPSfZcsTP5mqI+13q6VHMga0kjMXkf8fmafGksfT2iDYv5znr4hmG5B1PpfeWmJTqAwwf36pksE/TfGnuo/olFK4GJgUacEUGpy6PaI2FxYzJHiRsYDvIpsx9RfJYONgJHtfoxPGLf8ss3kSeAWOb2gevR+ns6UFHpVy1ofIqRYh90N2e3Jgs6aUXksCPIpRtK903IcRH+ftoWBcL8+r8thVQWe/evs0pcSyWohi3/xoi7DSG9P8ydIx15cXANV1pOSL2RRtiz2EH8TgbBMR/9wixFV5ezfbhpw9OdZ7dpb/u7czNSJSeRJC7dqTsnIyRIUqQGh8L9wKRwTa3TkXUoUpeRTePPnOEGai1PjtzXfcfr4OG5j1uX/3iCLL1aQPZVh1uUubYIeEc1a7/8/BWcoI1Bg2ME2bdt8KOEGiB3L+lHgBMerbZFdbj2G09HPxwdSFIc2kjLNia08rKKdXvzNQ25d/DLs6+J03VR+ts7a42YfFSwHOpFtzsLoe8=
  on:
    tags: true
    repo: hmaarrfk/nep29
    python: 3.6
